<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.2">
  <POU Name="BoxLoader" Id="{8c060388-5aea-4670-8177-a59a4980b218}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK BoxLoader
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="BoxLoader">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>